config/routes.rb
Kbase::Application.routes.draw do
  devise_for :users

  resources :pages

  root :to => 'pages#index'

end

app/models/page.rb
# http://haplesshero13.github.io/blog/2012/08/17/rails-syntax-highlighting-using-redcarpet/
class Pygmentize < Redcarpet::Render::HTML
  def block_code(code, language)
    Pygments.highlight(code, :lexer => language, :options => {})
  end
end

class Page < ActiveRecord::Base

  attr_accessible :body, :title, :public

  validates :title, :presence => true

  belongs_to :user

  def render
  	pygmentized = Pygmentize.new(:filter_html => true, :hard_wrap => true)
	markdown = Redcarpet::Markdown.new(pygmentized, :fenced_code_blocks => true, :autolink => true)
	markdown.render self.body
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    #@pages = Page.all
    @pages        = current_user.pages
    #@public_pages = Page.where("public = ? AND user_id IS NOT ?", true, current_user.id)
    @public_pages = Page.where("public = ? AND user_id != ?", true, current_user.id)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
    # @page = current_user.pages.find(params[:id])
    if @page.user == current_user
      @page = current_user.pages.find(params[:id])
    else
      @page = Page.where(:id => params[:id], :public => true).first
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  rescue Exception => e
    flash[:error] = "An error"
    @error = e.inspect
    render 'error'
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    # @page = Page.new
    @page = current_user.pages.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    # @page = Page.find(params[:id])
    @page = current_user.pages.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    # @page = Page.new(params[:page])
    @page = current_user.pages.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    # @page = Page.find(params[:id])
    @page = current_user.pages.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    # @page = Page.find(params[:id])
    @page = current_user.pages.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def icon(icon_class)
		'<i class="' + icon_class + '"></i>'
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kbase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if notice %> <p class="notice"><%= notice %></p> <% end %>
  <% if alert %>  <p class="alert"><%= alert %></p>   <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation" class="alert">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :placeholder => 'This is your new title' %>
  </div>
  <div class="field">
    <%= f.text_area :body, :placeholder => 'Lala' %>
  </div>
  <div class="field">
    <%= f.check_box :public %> This page is public
  </div>
  
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/pages/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
  	<% if @page && !@page.new_record? %>
    <a class="brand" href="#"><%= @page.title %></a>
      <li class="<%= 'active' if %w(show).include?(controller.action_name) %>">
      	<%= link_to icon('icon-eye-open').html_safe, @page %>
      </li>
	  <li class="<%= 'active' if %w(edit).include?(controller.action_name) %>">
	  	<%= link_to icon('icon-pencil').html_safe, edit_page_path(@page) %>
	  </li>
    <% else %>
      <li class="<%= 'active' if %w(new).include?(controller.action_name) %>">
        <%= link_to icon('icon-plus-sign').html_safe + ' Add Page', new_page_path %></li>
    <% end %>
    </ul>
    <ul class="nav pull-right">
  	  <li><%= link_to icon('icon-home').html_safe + " Knowledge Base", pages_path %></a></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
</div>

app/views/pages/edit.html.erb
<%= render 'nav' %>

<%= render 'form' %>

<%= link_to icon('icon-trash icon-white').html_safe + ' Delete', @page, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>

app/views/pages/error.html.erb
<%= render 'nav' %>

<div class="alert alert-error">Sorry, I made a mistake</div>
<pre>
  <%= @error %>
</pre>

app/views/pages/index.html.erb
<%= render 'nav' %>

<h3>My Pages</h3>

<table class="table table-striped table-condensed table-bordered">
<% @pages.each do |page| %>
  <tr>
  	<td class="public"><%= icon('icon-eye-open').html_safe if page.public %></td>
    <td class="title"><%= icon('icon-file').html_safe %> <%= link_to page.title, page %></td>
    <td class="updated_at"><%= icon('icon-time').html_safe %> <%= distance_of_time_in_words_to_now page.updated_at %> ago</td>
    <td class="email"><%= icon('icon-user').html_safe %> <%= page.user.email %></td>
  </tr>
<% end %>
</table>

<h3>Public Pages</h3>

<table class="table table-striped table-condensed table-bordered">
<% @public_pages.each do |page| %>
  <tr>
    <td class="title"><%= icon('icon-file').html_safe %> <%= link_to page.title, page %></td>
    <td class="updated_at"><%= icon('icon-time').html_safe %> <%= distance_of_time_in_words_to_now page.updated_at %> ago</td>
    <td class="email"><%= icon('icon-user').html_safe %> <%= page.user.email %></td>
  </tr>
<% end %>
</table>

app/views/pages/new.html.erb
<%= render 'nav' %>
<%= render 'form' %>

app/views/pages/show.html.erb
<%= render 'nav' %>

<% if notice %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<style>
<%= Pygments.css %>
</style>

<%=raw @page.render %>